@baseUrl=https://localhost:7074
@applicationId=test-app

POST {{baseUrl}}/ClinicalImpression
X-Ihis-SourceApplication: {{applicationId}}
Content-Type: application/fhir+json

{
	"resourceType": "ClinicalImpression",
  "extension": [
    {
      "url": "https://example.org/fhir/StructureDefinition/ClinicalImpression-CarePlan",
      "valueReference": {
        "reference": "CarePlan/1234",
        "display": "Initial Care Plan"
      }
    }
  ],
	"status": "completed",
	"subject": {
		"reference": "Patient/example"
	},
  "note": [
    {
      "text": "Patient presents with fever, fatigue"
    }
  ]
}

###
GET {{baseUrl}}/ClinicalImpression?note-content:contains=fever,breath
X-Ihis-SourceApplication: {{applicationId}}

###
GET {{baseUrl}}/ClinicalImpression?note-content:contains=fever&note-content:contains=fatigue
X-Ihis-SourceApplication: {{applicationId}}
###
GET {{baseUrl}}/ClinicalImpression?note-content:contains=fever,cough&note-content:contains=fatigue
X-Ihis-SourceApplication: {{applicationId}}
###
GET {{baseUrl}}/ClinicalImpression?note-content:contains=fever,cough&note-content:contains=fatigue,breath
X-Ihis-SourceApplication: {{applicationId}}

###
GET {{baseUrl}}/ClinicalImpression?ci-careplan=CarePlan/1234
X-Ihis-SourceApplication: {{applicationId}}


### serach partial sentense contains `,`
GET {{baseUrl}}/ClinicalImpression?note-content:contains=fever\,%20fatigue
X-Ihis-SourceApplication: {{applicationId}}

### 
POST {{baseUrl}}/ClinicalImpression/_search
X-Ihis-SourceApplication: {{applicationId}}
Content-Type: application/fhir+json

{
  "resourceType": "Parameters",
	"parameter": [
		{
			"name": "note-content:contains",
			"valueString": "fever\\, fatigue"
		}
	]
}

###
POST {{baseUrl}}/ClinicalImpression/_search
X-Ihis-SourceApplication: {{applicationId}}
Content-Type: application/x-www-form-urlencoded

note-content:contains=fever\,%20fatigue